### ISSUE TITLE
Update CI worfklow to use multiple jobs

### ISSUE THREAD

**Issue by shapeseas** [Watts-Lab/deliberation-lab-tools#31]
https://github.com/Watts-Lab/deliberation-lab-tools/blob/44ed37238581ecedcdb76c926676ec7e6840615f/.github/workflows/update.yml#L6C1-L12C28

Break into 3 jobs:

- [ ] validate-tag
- [ ] build-and-test
- [ ] publish

Use `needs` so that later jobs will not start if earlier jobs fail.
```
on:
  release:
    types: [created]

jobs:
  validate-tag:
    runs-on: ubuntu-latest
    steps:
     ...

  build-and-test:
    runs-on: ubuntu-latest
    needs: validate-tag
    steps:
    ...

  publish:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
    ...
```
