### ISSUE TITLE
[FEATURE]: In yaml, throw an error if referenced path is missing

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/deliberation-lab-tools#60]
### User Story

As an experiment designer, I want feedback to know if the file that I'm trying to reference doesn't exist, so that I can either create the file, or fix the path.

### Feature description

Put up a squiggly error underline thingy on paths for prompt files that don't exist.

For example, imagine I have a file at path `projects/css_lab/dl_collab/intro/consider_topic.md`, and I try and reference it from the wrong path, e.g.:
```yaml
        elements:
          - type: prompt
            file: projects/css_lab/dl_collab/consider_topic.md
```
Then I should get a warning that the path is invalid or the file is not found, or something.

### What would this feature enable?

Confidence that file paths are specified correctly.
